import { PrismaClient, ProjectType, Timeline, BudgetRange, LeadStatus } from "@prisma/client";

const prisma = new PrismaClient();

// Seed leads clustered around the Austin, TX metro area.
const leads = [
  { name: "Travis Boone", email: "travis.boone@gmail.com", phone: "512-555-0141", address: "4207 Shoal Creek Blvd, Austin, TX", lat: 30.3121, lng: -97.7442, projectType: ProjectType.POOL, description: "Backyard pool dig, roughly 16x32, sloped lot with limestone likely 4ft down. Need haul-away included.", timeline: Timeline.ONE_TO_THREE_MONTHS, budgetRange: BudgetRange.FROM_25K_TO_50K, status: LeadStatus.QUALIFIED, daysAgo: 43 },
  { name: "Maria Delgado", email: "mdelgado78@yahoo.com", phone: "512-555-0192", address: "1811 E 38th 1/2 St, Austin, TX", lat: 30.2999, lng: -97.7176, projectType: ProjectType.FOUNDATION_BASEMENT, description: "New ADU build in backyard, need pad excavation and pier holes. Plans in hand, permitted.", timeline: Timeline.ASAP, budgetRange: BudgetRange.FROM_10K_TO_25K, status: LeadStatus.CONTACTED, daysAgo: 41 },
  { name: "Chuck Reiner", email: "chuck@reinercustomhomes.com", phone: "512-555-0117", address: "Lot 14, Provence Subdivision, Dripping Springs, TX", lat: 30.2247, lng: -98.0292, projectType: ProjectType.GRADING_CLEARING, description: "Builder here - need 1.5 acre lot cleared and rough graded for spec home. Cedar removal, keep the oaks.", timeline: Timeline.ASAP, budgetRange: BudgetRange.FROM_10K_TO_25K, status: LeadStatus.QUALIFIED, daysAgo: 38 },
  { name: "Denise Okafor", email: "denise.okafor@outlook.com", phone: "737-555-0163", address: "9805 Curlew Dr, Austin, TX", lat: 30.1719, lng: -97.7911, projectType: ProjectType.SEPTIC, description: "Failed septic inspection on home purchase. Need old tank dug out and new conventional system trenched.", timeline: Timeline.ONE_TO_THREE_MONTHS, budgetRange: BudgetRange.FROM_10K_TO_25K, status: LeadStatus.CONTACTED, daysAgo: 36 },
  { name: "Bill Hartsell", email: "bhartsell@sbcglobal.net", phone: "512-555-0128", address: "308 Whispering Oaks, Georgetown, TX", lat: 30.6427, lng: -97.6789, projectType: ProjectType.DEMOLITION, description: "1960s detached garage, slab and all needs to go. Maybe 600 sqft. Want slab hauled off and hole backfilled.", timeline: Timeline.FLEXIBLE, budgetRange: BudgetRange.UNDER_10K, status: LeadStatus.REJECTED, daysAgo: 34 },
  { name: "Priya Raman", email: "priya.raman.atx@gmail.com", phone: "512-555-0154", address: "2404 Alta Vista Ave, Austin, TX", lat: 30.2455, lng: -97.7658, projectType: ProjectType.UTILITY_TRENCHING, description: "Trench ~180ft from house to new workshop for electric + water. Two live oak root zones to work around.", timeline: Timeline.THREE_TO_SIX_MONTHS, budgetRange: BudgetRange.UNDER_10K, status: LeadStatus.NEW, daysAgo: 31 },
  { name: "Frank Moreau", email: "fmoreau@moreaupools.com", phone: "512-555-0176", address: "Multiple sites, Lakeway, TX", lat: 30.3639, lng: -97.9725, projectType: ProjectType.POOL, description: "Pool contractor looking for a reliable dig sub. 3-4 digs a month in the Lakeway/Bee Cave area. Rock experience required.", timeline: Timeline.ASAP, budgetRange: BudgetRange.OVER_100K, status: LeadStatus.QUALIFIED, daysAgo: 28 },
  { name: "Janet Kowalski", email: "jkowalski1955@aol.com", phone: "512-555-0135", address: "606 Buttercup Creek Blvd, Cedar Park, TX", lat: 30.4894, lng: -97.8306, projectType: ProjectType.GRADING_CLEARING, description: "Drainage problem - backyard floods toward the house every storm. Need regrading and maybe a french drain trench.", timeline: Timeline.ASAP, budgetRange: BudgetRange.UNDER_10K, status: LeadStatus.CONTACTED, daysAgo: 26 },
  { name: "Marcus Webb", email: "marcus.webb@webbbuilt.com", phone: "737-555-0148", address: "1109 Gillespie Pl, Austin, TX", lat: 30.2359, lng: -97.7524, projectType: ProjectType.FOUNDATION_BASEMENT, description: "Full basement dig for custom home - rare for Austin, engineered plans ready. ~2000sqft footprint, 9ft depth.", timeline: Timeline.ONE_TO_THREE_MONTHS, budgetRange: BudgetRange.FROM_50K_TO_100K, status: LeadStatus.NEW, daysAgo: 24 },
  { name: "Soo-Jin Park", email: "soojin.park.tx@gmail.com", phone: "512-555-0183", address: "3506 Palomar Ln, Round Rock, TX", lat: 30.5321, lng: -97.6605, projectType: ProjectType.POOL, description: "Plunge pool, small yard with tight access - only a 5ft gate. Need mini excavator job, spoils hauled.", timeline: Timeline.THREE_TO_SIX_MONTHS, budgetRange: BudgetRange.FROM_10K_TO_25K, status: LeadStatus.NEW, daysAgo: 21 },
  { name: "Ray Gutierrez", email: "ray.g.construction@gmail.com", phone: "512-555-0107", address: "FM 1626, Manchaca, TX", lat: 30.1405, lng: -97.8331, projectType: ProjectType.UTILITY_TRENCHING, description: "Commercial site - 400ft of trench for 3-phase electrical conduit plus comms. Traffic control needed on shoulder.", timeline: Timeline.ASAP, budgetRange: BudgetRange.FROM_25K_TO_50K, status: LeadStatus.CONTACTED, daysAgo: 19 },
  { name: "Alicia Fontenot", email: "alicia.fontenot@icloud.com", phone: "737-555-0121", address: "205 Sunfish St, Lakeway, TX", lat: 30.3743, lng: -97.9861, projectType: ProjectType.DEMOLITION, description: "Fire-damaged home, insurance settled. Full teardown to slab, then slab removal. Asbestos survey already done, clean.", timeline: Timeline.ONE_TO_THREE_MONTHS, budgetRange: BudgetRange.FROM_25K_TO_50K, status: LeadStatus.QUALIFIED, daysAgo: 17 },
  { name: "Tom Brandt", email: "tbrandt@brandtranch.com", phone: "512-555-0169", address: "Brandt Ranch Rd, Liberty Hill, TX", lat: 30.6659, lng: -97.9225, projectType: ProjectType.GRADING_CLEARING, description: "New ranch entrance - 900ft caliche driveway cut and graded, plus culvert set at the county road.", timeline: Timeline.FLEXIBLE, budgetRange: BudgetRange.FROM_10K_TO_25K, status: LeadStatus.NEW, daysAgo: 14 },
  { name: "Nina Vasquez", email: "nina.vasquez@utexas.edu", phone: "512-555-0195", address: "5010 Avenue H, Austin, TX", lat: 30.3103, lng: -97.7228, projectType: ProjectType.OTHER, description: "Rainwater harvesting - two 5000gal cisterns to bury beside the house, plus trench to gutters. Weird one, I know.", timeline: Timeline.THREE_TO_SIX_MONTHS, budgetRange: BudgetRange.FROM_10K_TO_25K, status: LeadStatus.NEW, daysAgo: 12 },
  { name: "Dale Pruett", email: "dale.pruett@gmail.com", phone: "512-555-0112", address: "118 Coventry Rd, Buda, TX", lat: 30.0827, lng: -97.8422, projectType: ProjectType.SEPTIC, description: "New construction on 2 acres, need aerobic septic install - tank pit, spray field trenching, the works.", timeline: Timeline.ONE_TO_THREE_MONTHS, budgetRange: BudgetRange.FROM_10K_TO_25K, status: LeadStatus.NEW, daysAgo: 9 },
  { name: "Rebecca Stone", email: "rstone@stonelawatx.com", phone: "512-555-0187", address: "1204 The High Rd, West Lake Hills, TX", lat: 30.2836, lng: -97.8112, projectType: ProjectType.FOUNDATION_BASEMENT, description: "Hillside addition, engineer specs 14 drilled piers into limestone. Tight access, steep lot - not an easy one.", timeline: Timeline.THREE_TO_SIX_MONTHS, budgetRange: BudgetRange.FROM_50K_TO_100K, status: LeadStatus.NEW, daysAgo: 7 },
  { name: "Hector Alanis", email: "h.alanis.paving@gmail.com", phone: "737-555-0139", address: "E Pecan St, Pflugerville, TX", lat: 30.4427, lng: -97.6183, projectType: ProjectType.DEMOLITION, description: "Old strip center parking lot - 22,000 sqft of asphalt out, regrade for new surface. Can you crush on site?", timeline: Timeline.ASAP, budgetRange: BudgetRange.FROM_25K_TO_50K, status: LeadStatus.NEW, daysAgo: 5 },
  { name: "Lauren Choi", email: "lauren.choi.austin@gmail.com", phone: "512-555-0158", address: "7304 Lamplight Ln, Austin, TX", lat: 30.3557, lng: -97.7431, projectType: ProjectType.POOL, description: "Standard gunite pool dig, 14x28, flat yard, good access through side gate. Builder wants dig-only sub.", timeline: Timeline.ONE_TO_THREE_MONTHS, budgetRange: BudgetRange.UNDER_10K, status: LeadStatus.NEW, daysAgo: 3 },
  { name: "Gary Whitfield", email: "gwhitfield@whitfielddev.com", phone: "512-555-0102", address: "Tract 3, SH-130 & Pearce Ln, Del Valle, TX", lat: 30.1691, lng: -97.6217, projectType: ProjectType.GRADING_CLEARING, description: "12-acre commercial pad site - clearing, grubbing, cut/fill balance per civil plans. Bid package available.", timeline: Timeline.THREE_TO_SIX_MONTHS, budgetRange: BudgetRange.OVER_100K, status: LeadStatus.NEW, daysAgo: 2 },
  { name: "Emily Tran", email: "emily.tran92@gmail.com", phone: "737-555-0174", address: "2101 Faro Dr, Austin, TX", lat: 30.2762, lng: -97.6952, projectType: ProjectType.UTILITY_TRENCHING, description: "Sewer line replacement from house to street, roots got the old clay pipe. ~60ft, need it dug and backfilled after plumber.", timeline: Timeline.ASAP, budgetRange: BudgetRange.UNSURE, status: LeadStatus.NEW, daysAgo: 1 },
];

async function main() {
  await prisma.lead.deleteMany();
  for (const { daysAgo, ...lead } of leads) {
    const createdAt = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000);
    await prisma.lead.create({ data: { ...lead, createdAt } });
  }
  console.log(`Seeded ${leads.length} leads.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
